.TH "BO" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BO
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBAlojamento\fP"
.br
.RI "Purpose: Created by: João Barbosa Created on: 17/12/2024 17:32:51\&. "
.ti -1c
.RI "class \fBCheckInBO\fP"
.br
.RI "Purpose: Created by: João Barbosa Created on: 18/12/2024 16:30:50\&. "
.ti -1c
.RI "class \fBCliente\fP"
.br
.RI "Purpose: Created by: João Barbosa Created on: 17/12/2024 14:32:04\&. "
.ti -1c
.RI "interface \fBIAlojamento\fP"
.br
.RI "Purpose: Created by: João Barbosa Created on: 17/12/2024 14:32:45\&. "
.ti -1c
.RI "class \fBReservaBO\fP"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
