.TH "BO.CheckInBO" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BO.CheckInBO \- Purpose: Created by: João Barbosa Created on: 18/12/2024 16:30:50\&.  

.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBCheckInBO\fP (int codigoReserva)"
.br
.RI "Construtor que inicializa uma nova instância da classe \fBCheckInBO\fP com um código de reserva\&. "
.in -1c
.SS "Propriedades"

.in +1c
.ti -1c
.RI "int \fBCodigoReserva\fP\fR [get, set]\fP"
.br
.RI "Propriedade que obtém ou define o código da reserva\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Purpose: Created by: João Barbosa Created on: 18/12/2024 16:30:50\&. 


.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "BO\&.CheckInBO\&.CheckInBO (int codigoReserva)"

.PP
Construtor que inicializa uma nova instância da classe \fBCheckInBO\fP com um código de reserva\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP Código da reserva associada ao check-in\&.
.RE
.PP

.SH "Documentação das propriedades"
.PP 
.SS "int BO\&.CheckInBO\&.CodigoReserva\fR [get]\fP, \fR [set]\fP"

.PP
Propriedade que obtém ou define o código da reserva\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
