.TH "BO.Cliente" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BO.Cliente \- Purpose: Created by: João Barbosa Created on: 17/12/2024 14:32:04\&.  

.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBCliente\fP ()"
.br
.RI "Construtor padrão da classe \fBCliente\fP\&. Inicializa o nome como uma string vazia e o número de identificação como '0'\&. "
.ti -1c
.RI "\fBCliente\fP (string nome, int numIdentificacao)"
.br
.RI "Construtor com parâmetros da classe \fBCliente\fP\&. "
.in -1c
.SS "Membros públicos estáticos"

.in +1c
.ti -1c
.RI "static \fBCliente\fP \fBCriaCliente\fP (string nome, int numIdentificacao)"
.br
.in -1c
.SS "Propriedades"

.in +1c
.ti -1c
.RI "string \fBNome\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define o nome do cliente\&. "
.ti -1c
.RI "int \fBNumIdentificacao\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define o número de identificação do cliente\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Purpose: Created by: João Barbosa Created on: 17/12/2024 14:32:04\&. 


.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "BO\&.Cliente\&.Cliente ()"

.PP
Construtor padrão da classe \fBCliente\fP\&. Inicializa o nome como uma string vazia e o número de identificação como '0'\&. 
.SS "BO\&.Cliente\&.Cliente (string nome, int numIdentificacao)"

.PP
Construtor com parâmetros da classe \fBCliente\fP\&. 
.PP
\fBParâmetros\fP
.RS 4
\fInome\fP Nome do cliente\&.
.br
\fInumIdentificacao\fP Número de identificação do cliente\&.
.RE
.PP

.SH "Documentação das funções"
.PP 
.SS "static \fBCliente\fP BO\&.Cliente\&.CriaCliente (string nome, int numIdentificacao)\fR [static]\fP"

.SH "Documentação das propriedades"
.PP 
.SS "string BO\&.Cliente\&.Nome\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define o nome do cliente\&. 
.SS "int BO\&.Cliente\&.NumIdentificacao\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define o número de identificação do cliente\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
