.TH "BO.IAlojamento" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BO.IAlojamento \- Purpose: Created by: João Barbosa Created on: 17/12/2024 14:32:45\&.  

.SH SYNOPSIS
.br
.PP
.PP
Herdado por \fBBO\&.Alojamento\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "short \fBReservarQuartos\fP (DateTime dataEntrada, DateTime dataSaida, int quantidadeQuartos)"
.br
.RI "Realiza a reserva de uma quantidade de quartos no alojamento para o intervalo de datas especificado\&. "
.ti -1c
.RI "bool \fBLibertaQuartos\fP (int quantidade)"
.br
.RI "Liberta uma quantidade especificada de quartos\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Purpose: Created by: João Barbosa Created on: 17/12/2024 14:32:45\&. 


.SH "Documentação das funções"
.PP 
.SS "bool BO\&.IAlojamento\&.LibertaQuartos (int quantidade)"

.PP
Liberta uma quantidade especificada de quartos\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIquantidade\fP Quantidade de quartos a libetar\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se a operação for bem-sucedida; caso contrário, \fRfalse\fP\&.
.RE
.PP

.PP
Implementado em \fBBO\&.Alojamento\fP\&.
.SS "short BO\&.IAlojamento\&.ReservarQuartos (DateTime dataEntrada, DateTime dataSaida, int quantidadeQuartos)"

.PP
Realiza a reserva de uma quantidade de quartos no alojamento para o intervalo de datas especificado\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIdataEntrada\fP Data de início da reserva\&.
.br
\fIdataSaida\fP Data de término da reserva\&.
.br
\fIquantidadeQuartos\fP Número de quartos a serem reservados\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se a reserva foi realizada com sucesso; caso contrário, \fRfalse\fP\&.
.RE
.PP

.PP
Implementado em \fBBO\&.Alojamento\fP\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
