.TH "Referência do diretório dados" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório dados
.SH SYNOPSIS
.br
.PP
.SS "Diretórios"

.in +1c
.ti -1c
.RI "diretório \fBobj\fP"
.br
.ti -1c
.RI "diretório \fBProperties\fP"
.br
.in -1c
.SS "Ficheiros"

.in +1c
.ti -1c
.RI "ficheiro \fBCheckIn\&.cs\fP"
.br
.ti -1c
.RI "ficheiro \fBCheckInConcreto\&.cs\fP"
.br
.ti -1c
.RI "ficheiro \fBCheckInReserva\&.cs\fP"
.br
.ti -1c
.RI "ficheiro \fBReserva\&.cs\fP"
.br
.ti -1c
.RI "ficheiro \fBReservas\&.cs\fP"
.br
.in -1c
