.TH "Referência do diretório BO" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório BO
.SH SYNOPSIS
.br
.PP
.SS "Diretórios"

.in +1c
.ti -1c
.RI "diretório \fBobj\fP"
.br
.ti -1c
.RI "diretório \fBProperties\fP"
.br
.in -1c
.SS "Ficheiros"

.in +1c
.ti -1c
.RI "ficheiro \fBAlojamentoBO\&.cs\fP"
.br
.ti -1c
.RI "ficheiro \fBCheckInBO\&.cs\fP"
.br
.ti -1c
.RI "ficheiro \fBClienteBO\&.cs\fP"
.br
.ti -1c
.RI "ficheiro \fBIAlojamento\&.cs\fP"
.br
.ti -1c
.RI "ficheiro \fBReservasBO\&.cs\fP"
.br
.in -1c
