.TH "dados.Reservas" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dados.Reservas
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "int \fBAdicionarReservaBO\fP (\fBReservaBO\fP reservaBO)"
.br
.RI "Adiciona uma nova reserva \fBBO\fP à lista, convertendo-a para \fBdados\&.Reserva\fP\&. "
.ti -1c
.RI "int \fBAdicionarReserva\fP (\fBReserva\fP reserva)"
.br
.RI "Adiciona uma nova reserva à lista\&. "
.ti -1c
.RI "bool \fBRemoverReserva\fP (int codigoReserva)"
.br
.RI "Remove uma reserva pelo código\&. "
.ti -1c
.RI "decimal \fBCalcularPrecoReserva\fP (int codigoReserva, decimal precoPorNoite)"
.br
.RI "Calcula o preço total da reserva\&. "
.ti -1c
.RI "bool \fBReservaExiste\fP (int codigoReserva)"
.br
.RI "Verifica se uma reserva existe na lista de reservas\&. "
.ti -1c
.RI "bool \fBGuardarReservas\fP (string caminhoFicheiro)"
.br
.RI "Guarda a lista de reservas em um ficheiro binário especificado\&. "
.ti -1c
.RI "bool \fBCarregarReservas\fP (string caminhoFicheiro)"
.br
.RI "Carrega a lista de reservas a partir de um ficheiro binário especificado\&. "
.in -1c
.SS "Atributos Públicos Estáticos"

.in +1c
.ti -1c
.RI "static List< \fBReserva\fP > \fBreservas\fP = new List<\fBReserva\fP>()"
.br
.in -1c
.SS "Propriedades"

.in +1c
.ti -1c
.RI "int \fBCodigoReservaAtual\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define o código da reserva atual\&. "
.in -1c
.SH "Documentação das funções"
.PP 
.SS "int dados\&.Reservas\&.AdicionarReserva (\fBReserva\fP reserva)"

.PP
Adiciona uma nova reserva à lista\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIreserva\fP \fBReserva\fP a ser adicionada
.RE
.PP
\fBRetorna\fP
.RS 4
Código da reserva ou -1 se inválida
.RE
.PP

.SS "int dados\&.Reservas\&.AdicionarReservaBO (\fBReservaBO\fP reservaBO)"

.PP
Adiciona uma nova reserva \fBBO\fP à lista, convertendo-a para \fBdados\&.Reserva\fP\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIreservaBO\fP ReservaBO a ser adicionada\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Código da reserva gerado ou -1 se a reserva for inválida\&.
.RE
.PP

.SS "decimal dados\&.Reservas\&.CalcularPrecoReserva (int codigoReserva, decimal precoPorNoite)"

.PP
Calcula o preço total da reserva\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP Código da reserva
.br
\fIprecoPorNoite\fP Preço por noite
.RE
.PP
\fBRetorna\fP
.RS 4
Preço total ou -1 se reserva não for encontrada
.RE
.PP

.SS "bool dados\&.Reservas\&.CarregarReservas (string caminhoFicheiro)"

.PP
Carrega a lista de reservas a partir de um ficheiro binário especificado\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP O caminho completo do ficheiro de onde as reservas serão carregadas\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se o processo de carregamento for bem-sucedido\&.
.RE
.PP
\fBExcepções\fP
.RS 4
\fIFicheiroNaoEncontradoException\fP Lançada quando o ficheiro especificado não é encontrado\&.
.br
\fIAcessoNegadoException\fP Lançada quando não há permissão para acessar o ficheiro\&.
.br
\fIErroDeIOException\fP Lançada quando ocorre um erro de entrada/saída ao acessar o ficheiro\&.
.br
\fISerializacaoException\fP Lançada quando ocorre um erro ao desserializar os dados\&.
.br
\fIBaseReservaException\fP Lançada para erros genéricos não específicos (-4)\&.
.RE
.PP

.SS "bool dados\&.Reservas\&.GuardarReservas (string caminhoFicheiro)"

.PP
Guarda a lista de reservas em um ficheiro binário especificado\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP O caminho completo do ficheiro onde as reservas serão guardadas\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se o processo de guardar for bem-sucedido\&.
.RE
.PP
\fBExcepções\fP
.RS 4
\fIAcessoNegadoException\fP Lançada quando não há permissão para acessar o ficheiro\&.
.br
\fIErroDeIOException\fP Lançada quando ocorre um erro de entrada/saída ao acessar o ficheiro\&.
.br
\fISerializacaoException\fP Lançada quando ocorre um erro ao serializar os dados\&.
.br
\fIBaseReservaException\fP Lançada para erros genéricos não específicos (-4)\&.
.RE
.PP

.SS "bool dados\&.Reservas\&.RemoverReserva (int codigoReserva)"

.PP
Remove uma reserva pelo código\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP Código da reserva
.RE
.PP
\fBRetorna\fP
.RS 4
True se removida com sucesso, False caso contrário
.RE
.PP

.SS "bool dados\&.Reservas\&.ReservaExiste (int codigoReserva)"

.PP
Verifica se uma reserva existe na lista de reservas\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP Código da reserva a ser verificada\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se a reserva existir, caso contrário, \fRfalse\fP\&.
.RE
.PP

.SH "Documentação dos dados membro"
.PP 
.SS "List<\fBReserva\fP> dados\&.Reservas\&.reservas = new List<\fBReserva\fP>()\fR [static]\fP"

.SH "Documentação das propriedades"
.PP 
.SS "int dados\&.Reservas\&.CodigoReservaAtual\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define o código da reserva atual\&. O código da reserva atual\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
