.TH "dados.CheckIn" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dados.CheckIn
.SH SYNOPSIS
.br
.PP
.PP
Herdado por \fBdados\&.CheckInConcreto\fP e \fBdados\&.GestaoCheckIn\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBCheckIn\fP (int codigoReserva)"
.br
.RI "Construtor da classe \fBCheckIn\fP\&. Inicializa a propriedade CodigoReserva com o valor fornecido e define a propriedade DataHoraCheckIn como null, indicando que o check-in ainda não foi realizado\&. "
.ti -1c
.RI "bool \fBAdicionarCheckIn\fP (\fBCheckIn\fP checkIn)"
.br
.RI "Método abstrato que deve ser implementado para adicionar um check-in\&. "
.ti -1c
.RI "bool \fBGuardarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "Método abstrato que deve ser implementado para guardar os check-ins em um ficheiro\&. "
.ti -1c
.RI "bool \fBCarregarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "Método abstrato que deve ser implementado para carregar os check-ins de um ficheiro\&. "
.ti -1c
.RI "bool \fBCheckInRealizado\fP ()"
.br
.RI "Método abstrato que deve ser implementado para verificar se o check-in foi realizado\&. "
.ti -1c
.RI "void \fBRegistarCheckIn\fP (DateTime dataHora)"
.br
.RI "Método responsável por registrar a data e hora do check-in\&. "
.in -1c
.SS "Propriedades"

.in +1c
.ti -1c
.RI "int \fBCodigoReserva\fP\fR [get, set]\fP"
.br
.RI "Propriedade que representa o código da reserva associada ao check-in\&. "
.ti -1c
.RI "DateTime? \fBDataHoraCheckIn\fP\fR [get, set]\fP"
.br
.RI "Propriedade que representa a data e hora em que o check-in foi realizado\&. Se não houver check-in, o valor será null\&. "
.in -1c
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "dados\&.CheckIn\&.CheckIn (int codigoReserva)"

.PP
Construtor da classe \fBCheckIn\fP\&. Inicializa a propriedade CodigoReserva com o valor fornecido e define a propriedade DataHoraCheckIn como null, indicando que o check-in ainda não foi realizado\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP Código da reserva associada ao check-in\&.
.RE
.PP

.SH "Documentação das funções"
.PP 
.SS "bool dados\&.CheckIn\&.AdicionarCheckIn (\fBCheckIn\fP checkIn)\fR [abstract]\fP"

.PP
Método abstrato que deve ser implementado para adicionar um check-in\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcheckIn\fP Objeto do tipo \fBCheckIn\fP que será adicionado\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna true se o check-in for adicionado com sucesso, caso contrário, retorna false\&.
.RE
.PP

.SS "bool dados\&.CheckIn\&.CarregarCheckIns (string caminhoFicheiro)\fR [abstract]\fP"

.PP
Método abstrato que deve ser implementado para carregar os check-ins de um ficheiro\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP Caminho do ficheiro de onde os check-ins serão carregados\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna true se os check-ins forem carregados com sucesso, caso contrário, retorna false\&.
.RE
.PP

.SS "bool dados\&.CheckIn\&.CheckInRealizado ()\fR [abstract]\fP"

.PP
Método abstrato que deve ser implementado para verificar se o check-in foi realizado\&. 
.PP
\fBRetorna\fP
.RS 4
Retorna true se o check-in foi realizado, caso contrário, retorna false\&.
.RE
.PP

.SS "bool dados\&.CheckIn\&.GuardarCheckIns (string caminhoFicheiro)\fR [abstract]\fP"

.PP
Método abstrato que deve ser implementado para guardar os check-ins em um ficheiro\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP Caminho do ficheiro onde os check-ins serão guardados\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna true se os check-ins forem guardados com sucesso, caso contrário, retorna false\&.
.RE
.PP

.SS "void dados\&.CheckIn\&.RegistarCheckIn (DateTime dataHora)"

.PP
Método responsável por registrar a data e hora do check-in\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIdataHora\fP A data e hora do check-in a ser registrado\&.
.RE
.PP

.SH "Documentação das propriedades"
.PP 
.SS "int dados\&.CheckIn\&.CodigoReserva\fR [get]\fP, \fR [set]\fP"

.PP
Propriedade que representa o código da reserva associada ao check-in\&. 
.SS "DateTime? dados\&.CheckIn\&.DataHoraCheckIn\fR [get]\fP, \fR [set]\fP"

.PP
Propriedade que representa a data e hora em que o check-in foi realizado\&. Se não houver check-in, o valor será null\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
