.TH "dados.Reserva" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dados.Reserva \- Purpose: Created by: João Barbosa Created on: 17/12/2024 14:36:54\&.  

.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBReserva\fP (int numIdentificacao, int numAlojamento, DateTime dataEntrada, DateTime dataSaida, int quantidadeQuartos)"
.br
.RI "Inicializa uma nova instância da classe \fBReserva\fP\&. "
.in -1c
.SS "Membros públicos estáticos"

.in +1c
.ti -1c
.RI "static \fBReserva\fP \fBCriaReserva\fP (int numIdentificacao, int numAlojamento, DateTime dataEntrada, DateTime dataSaida, int quantidadeQuartos)"
.br
.RI "Inicializa uma nova instância da classe \fBReserva\fP\&. "
.in -1c
.SS "Propriedades"

.in +1c
.ti -1c
.RI "int \fBNumIdentificacao\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define o número de identificação do Cliente\&. "
.ti -1c
.RI "int \fBNumAlojamento\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define o número de Identificação do Alojamento\&. "
.ti -1c
.RI "DateTime \fBDataEntrada\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define a data de entrada na reserva\&. "
.ti -1c
.RI "DateTime \fBDataSaida\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define a data de saída na reserva\&. "
.ti -1c
.RI "int \fBQuantidadeQuartos\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define a quantidade de quartos reservados\&. "
.ti -1c
.RI "DateTime? \fBDataHoraCheckIn\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define a data e hora do check-in, se realizado\&. "
.ti -1c
.RI "int \fBCodigoReserva\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define o código da reserva\&. "
.ti -1c
.RI "string \fBStatus\fP\fR [get, set]\fP"
.br
.RI "Obtém ou define o estado da reserva (ativo, cancelado, expirado) "
.in -1c
.SH "Descrição detalhada"
.PP 
Purpose: Created by: João Barbosa Created on: 17/12/2024 14:36:54\&. 


.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "dados\&.Reserva\&.Reserva (int numIdentificacao, int numAlojamento, DateTime dataEntrada, DateTime dataSaida, int quantidadeQuartos)"

.PP
Inicializa uma nova instância da classe \fBReserva\fP\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcliente\fP Cliente que fez a reserva\&.
.br
\fIalojamento\fP Alojamento onde será feita a reserva\&.
.br
\fIdataEntrada\fP Data de entrada na reserva\&.
.br
\fIdataSaida\fP Data de saída na reserva\&.
.br
\fIquantidadeQuartos\fP Quantidade de quartos a serem reservados\&.
.RE
.PP

.SH "Documentação das funções"
.PP 
.SS "static \fBReserva\fP dados\&.Reserva\&.CriaReserva (int numIdentificacao, int numAlojamento, DateTime dataEntrada, DateTime dataSaida, int quantidadeQuartos)\fR [static]\fP"

.PP
Inicializa uma nova instância da classe \fBReserva\fP\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcliente\fP Pessoa cliente que realizou a reserva\&.
.br
\fIalojamento\fP Alojamento onde será realizada a reserva\&.
.br
\fIdataEntrada\fP Data prevista para entrada na reserva\&.
.br
\fIdataSaida\fP Data prevista para saída da reserva\&.
.br
\fIquantidadeQuartos\fP Quantidade de quartos incluídos na reserva\&.
.RE
.PP

.SH "Documentação das propriedades"
.PP 
.SS "int dados\&.Reserva\&.CodigoReserva\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define o código da reserva\&. 
.SS "DateTime dados\&.Reserva\&.DataEntrada\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define a data de entrada na reserva\&. 
.SS "DateTime? dados\&.Reserva\&.DataHoraCheckIn\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define a data e hora do check-in, se realizado\&. 
.SS "DateTime dados\&.Reserva\&.DataSaida\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define a data de saída na reserva\&. 
.SS "int dados\&.Reserva\&.NumAlojamento\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define o número de Identificação do Alojamento\&. 
.SS "int dados\&.Reserva\&.NumIdentificacao\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define o número de identificação do Cliente\&. 
.SS "int dados\&.Reserva\&.QuantidadeQuartos\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define a quantidade de quartos reservados\&. 
.SS "string dados\&.Reserva\&.Status\fR [get]\fP, \fR [set]\fP"

.PP
Obtém ou define o estado da reserva (ativo, cancelado, expirado) 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
