.TH "dados.CheckInConcreto" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dados.CheckInConcreto \- Purpose: Created by: João Barbosa Created on: 18/12/2024 16:11:51\&.  

.SH SYNOPSIS
.br
.PP
.PP
Derivada de \fBdados\&.CheckIn\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBCheckInConcreto\fP (int codigoReserva)"
.br
.RI "Construtor da classe \fBCheckInConcreto\fP que inicializa um novo objeto com o código da reserva\&. "
.ti -1c
.RI "\fBCheckInConcreto\fP (int codigoReserva, DateTime dataHoraCheckIn)"
.br
.RI "Construtor da classe \fBCheckInConcreto\fP que inicializa um novo objeto com o código da reserva e a data/hora do check-in\&. "
.ti -1c
.RI "override bool \fBAdicionarCheckIn\fP (\fBCheckIn\fP checkIn)"
.br
.RI "Adiciona um check-in à lista de check-ins\&. "
.ti -1c
.RI "override bool \fBGuardarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "guarda os check-ins em um ficheiro\&. "
.ti -1c
.RI "override bool \fBCarregarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "Carrega os check-ins a partir de um ficheiro\&. "
.ti -1c
.RI "override bool \fBCheckInRealizado\fP ()"
.br
.RI "Verifica se o check-in foi realizado com base na data e hora do check-in\&. "
.in -1c

Membros públicos herdados de \fBdados\&.CheckIn\fP
.in +1c
.ti -1c
.RI "\fBCheckIn\fP (int codigoReserva)"
.br
.RI "Construtor da classe \fBCheckIn\fP\&. Inicializa a propriedade CodigoReserva com o valor fornecido e define a propriedade DataHoraCheckIn como null, indicando que o check-in ainda não foi realizado\&. "
.ti -1c
.RI "bool \fBAdicionarCheckIn\fP (\fBCheckIn\fP checkIn)"
.br
.RI "Método abstrato que deve ser implementado para adicionar um check-in\&. "
.ti -1c
.RI "bool \fBGuardarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "Método abstrato que deve ser implementado para guardar os check-ins em um ficheiro\&. "
.ti -1c
.RI "bool \fBCarregarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "Método abstrato que deve ser implementado para carregar os check-ins de um ficheiro\&. "
.ti -1c
.RI "bool \fBCheckInRealizado\fP ()"
.br
.RI "Método abstrato que deve ser implementado para verificar se o check-in foi realizado\&. "
.ti -1c
.RI "void \fBRegistarCheckIn\fP (DateTime dataHora)"
.br
.RI "Método responsável por registrar a data e hora do check-in\&. "
.in -1c
.SS "Outros membros herdados"


Propriedades herdados de \fBdados\&.CheckIn\fP
.in +1c
.ti -1c
.RI "int \fBCodigoReserva\fP\fR [get, set]\fP"
.br
.RI "Propriedade que representa o código da reserva associada ao check-in\&. "
.ti -1c
.RI "DateTime? \fBDataHoraCheckIn\fP\fR [get, set]\fP"
.br
.RI "Propriedade que representa a data e hora em que o check-in foi realizado\&. Se não houver check-in, o valor será null\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Purpose: Created by: João Barbosa Created on: 18/12/2024 16:11:51\&. 


.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "dados\&.CheckInConcreto\&.CheckInConcreto (int codigoReserva)"

.PP
Construtor da classe \fBCheckInConcreto\fP que inicializa um novo objeto com o código da reserva\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP Código da reserva que será associado ao check-in concreto\&.
.RE
.PP

.SS "dados\&.CheckInConcreto\&.CheckInConcreto (int codigoReserva, DateTime dataHoraCheckIn)"

.PP
Construtor da classe \fBCheckInConcreto\fP que inicializa um novo objeto com o código da reserva e a data/hora do check-in\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP Código da reserva que será associado ao check-in concreto\&.
.br
\fIdataHoraCheckIn\fP Data e hora do check-in que será registrado\&.
.RE
.PP

.SH "Documentação das funções"
.PP 
.SS "override bool dados\&.CheckInConcreto\&.AdicionarCheckIn (\fBCheckIn\fP checkIn)"

.PP
Adiciona um check-in à lista de check-ins\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcheckIn\fP Objeto do tipo \fBCheckIn\fP que representa o check-in a ser adicionado\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna true, indicando que o check-in foi adicionado com sucesso\&. A lógica de adição pode ser ajustada conforme necessário\&.
.RE
.PP

.SS "override bool dados\&.CheckInConcreto\&.CarregarCheckIns (string caminhoFicheiro)"

.PP
Carrega os check-ins a partir de um ficheiro\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP Caminho do ficheiro de onde os check-ins serão carregados\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna true, indicando que os check-ins foram carregados com sucesso\&. A lógica de carregamento pode ser ajustada conforme necessário\&.
.RE
.PP

.SS "override bool dados\&.CheckInConcreto\&.CheckInRealizado ()"

.PP
Verifica se o check-in foi realizado com base na data e hora do check-in\&. 
.PP
\fBRetorna\fP
.RS 4
Retorna true se o check-in foi realizado (ou seja, se a data/hora do check-in foi definida), caso contrário retorna false\&.
.RE
.PP

.SS "override bool dados\&.CheckInConcreto\&.GuardarCheckIns (string caminhoFicheiro)"

.PP
guarda os check-ins em um ficheiro\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP Caminho do ficheiro onde os check-ins serão guadados\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna true, indicando que os check-ins foram guardados com sucesso\&. A lógica de guardar pode ser ajustada conforme necessário\&.
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
