.TH "dados.GestaoCheckIn" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dados.GestaoCheckIn
.SH SYNOPSIS
.br
.PP
.PP
Derivada de \fBdados\&.CheckIn\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBGestaoCheckIn\fP (int codigoReserva)"
.br
.RI "Inicializa uma nova instância da classe \fBGestaoCheckIn\fP\&. "
.ti -1c
.RI "bool \fBAdicionarCheckIn\fP (\fBCheckInBO\fP checkInBO)"
.br
.RI "Adiciona um novo check-in à lista de check-ins após convertê-lo de CheckInBO para \fBCheckInConcreto\fP\&. "
.ti -1c
.RI "bool \fBRealizarCheckIn\fP (int codigoReserva)"
.br
.RI "Realiza o check-in para a reserva especificada, criando um novo objeto \fBCheckInConcreto\fP e adicionando-o à lista de check-ins\&. "
.ti -1c
.RI "override bool \fBAdicionarCheckIn\fP (\fBCheckIn\fP checkIn)"
.br
.RI "Adiciona um check-in à lista de check-ins caso ele já tenha sido realizado\&. "
.ti -1c
.RI "override bool \fBGuardarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "Guarda a lista de check-ins no ficheiro especificado\&. "
.ti -1c
.RI "override bool \fBCarregarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "Carrega a lista de check-ins a partir de um ficheiro\&. "
.ti -1c
.RI "override bool \fBCheckInRealizado\fP ()"
.br
.RI "Verifica se o check-in foi realizado\&. "
.in -1c

Membros públicos herdados de \fBdados\&.CheckIn\fP
.in +1c
.ti -1c
.RI "\fBCheckIn\fP (int codigoReserva)"
.br
.RI "Construtor da classe \fBCheckIn\fP\&. Inicializa a propriedade CodigoReserva com o valor fornecido e define a propriedade DataHoraCheckIn como null, indicando que o check-in ainda não foi realizado\&. "
.ti -1c
.RI "bool \fBAdicionarCheckIn\fP (\fBCheckIn\fP checkIn)"
.br
.RI "Método abstrato que deve ser implementado para adicionar um check-in\&. "
.ti -1c
.RI "bool \fBGuardarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "Método abstrato que deve ser implementado para guardar os check-ins em um ficheiro\&. "
.ti -1c
.RI "bool \fBCarregarCheckIns\fP (string caminhoFicheiro)"
.br
.RI "Método abstrato que deve ser implementado para carregar os check-ins de um ficheiro\&. "
.ti -1c
.RI "bool \fBCheckInRealizado\fP ()"
.br
.RI "Método abstrato que deve ser implementado para verificar se o check-in foi realizado\&. "
.ti -1c
.RI "void \fBRegistarCheckIn\fP (DateTime dataHora)"
.br
.RI "Método responsável por registrar a data e hora do check-in\&. "
.in -1c
.SS "Atributos Públicos Estáticos"

.in +1c
.ti -1c
.RI "static List< \fBCheckIn\fP > \fBlistaCheckIns\fP = new List<\fBCheckIn\fP>()"
.br
.in -1c
.SS "Outros membros herdados"


Propriedades herdados de \fBdados\&.CheckIn\fP
.in +1c
.ti -1c
.RI "int \fBCodigoReserva\fP\fR [get, set]\fP"
.br
.RI "Propriedade que representa o código da reserva associada ao check-in\&. "
.ti -1c
.RI "DateTime? \fBDataHoraCheckIn\fP\fR [get, set]\fP"
.br
.RI "Propriedade que representa a data e hora em que o check-in foi realizado\&. Se não houver check-in, o valor será null\&. "
.in -1c
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "dados\&.GestaoCheckIn\&.GestaoCheckIn (int codigoReserva)"

.PP
Inicializa uma nova instância da classe \fBGestaoCheckIn\fP\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP O código da reserva associada ao check-in\&.
.RE
.PP

.SH "Documentação das funções"
.PP 
.SS "override bool dados\&.GestaoCheckIn\&.AdicionarCheckIn (\fBCheckIn\fP checkIn)"

.PP
Adiciona um check-in à lista de check-ins caso ele já tenha sido realizado\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcheckIn\fP Objeto do tipo \fBCheckIn\fP a ser adicionado\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se o check-in foi adicionado com sucesso; retorna \fRfalse\fP caso contrário\&. 
.RE
.PP

.SS "bool dados\&.GestaoCheckIn\&.AdicionarCheckIn (\fBCheckInBO\fP checkInBO)"

.PP
Adiciona um novo check-in à lista de check-ins após convertê-lo de CheckInBO para \fBCheckInConcreto\fP\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcheckInBO\fP O objeto CheckInBO que contém os dados do check-in a ser adicionado\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP após adicionar o check-in à lista\&.
.RE
.PP

.SS "override bool dados\&.GestaoCheckIn\&.CarregarCheckIns (string caminhoFicheiro)"

.PP
Carrega a lista de check-ins a partir de um ficheiro\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP Caminho do ficheiro a ser carregado\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se o carregamento for bem-sucedido\&.
.RE
.PP
\fBExcepções\fP
.RS 4
\fIFicheiroNaoEncontradoException\fP Lançada se o ficheiro não existir\&.
.br
\fIAcessoNegadoException\fP Sem permissão para acessar o ficheiro\&.
.br
\fIErroDeIOException\fP Erro ao carregar do ficheiro\&.
.br
\fISerializacaoException\fP Erro durante a desserialização dos dados\&.
.br
\fIBaseReservaException\fP Erro genérico com código '-4'\&.
.RE
.PP

.SS "override bool dados\&.GestaoCheckIn\&.CheckInRealizado ()"

.PP
Verifica se o check-in foi realizado\&. 
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se o check-in foi realizado; caso contrário, \fRfalse\fP\&.
.RE
.PP

.SS "override bool dados\&.GestaoCheckIn\&.GuardarCheckIns (string caminhoFicheiro)"

.PP
Guarda a lista de check-ins no ficheiro especificado\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP Caminho do ficheiro onde os check-ins serão guardados\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se guardar for bem-sucedido\&.
.RE
.PP
\fBExcepções\fP
.RS 4
\fIAcessoNegadoException\fP Sem permissão para acessar o ficheiro\&.
.br
\fIErroDeIOException\fP Erro ao guardar no ficheiro\&.
.br
\fISerializacaoException\fP Erro durante a serialização dos dados\&.
.br
\fIBaseReservaException\fP Erro genérico com código '-4'\&.
.RE
.PP

.SS "bool dados\&.GestaoCheckIn\&.RealizarCheckIn (int codigoReserva)"

.PP
Realiza o check-in para a reserva especificada, criando um novo objeto \fBCheckInConcreto\fP e adicionando-o à lista de check-ins\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP Código da reserva para a qual o check-in será realizado\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se o check-in for realizado com sucesso, ou \fRfalse\fP caso contrário\&.
.RE
.PP

.SH "Documentação dos dados membro"
.PP 
.SS "List<\fBCheckIn\fP> dados\&.GestaoCheckIn\&.listaCheckIns = new List<\fBCheckIn\fP>()\fR [static]\fP"


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
