.TH "dados" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dados
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBCheckIn\fP"
.br
.ti -1c
.RI "class \fBCheckInConcreto\fP"
.br
.RI "Purpose: Created by: João Barbosa Created on: 18/12/2024 16:11:51\&. "
.ti -1c
.RI "class \fBGestaoCheckIn\fP"
.br
.ti -1c
.RI "class \fBReserva\fP"
.br
.RI "Purpose: Created by: João Barbosa Created on: 17/12/2024 14:36:54\&. "
.ti -1c
.RI "class \fBReservas\fP"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
