.TH "Regras.RegrasCheckIn" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Regras.RegrasCheckIn \- Purpose: Created by: João Barbosa Created on: 18/12/2024 11:23:58\&.  

.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBRegrasCheckIn\fP ()"
.br
.RI "Construtor da classe \fBRegrasCheckIn\fP\&. Inicializa uma nova instância de GestaoCheckIn\&. "
.ti -1c
.RI "bool \fBAdicionarCheckInRegra\fP (\fBCheckInBO\fP checkIn)"
.br
.RI "Adiciona um check-in à gestão de check-ins\&. "
.ti -1c
.RI "bool \fBGuardarCheckInsRegra\fP (string caminhoFicheiro)"
.br
.RI "Guarda os check-ins em um ficheiro\&. "
.ti -1c
.RI "bool \fBCarregarCheckInsRegra\fP (string caminhoFicheiro)"
.br
.RI "Carrega os check-ins a partir de um ficheiro\&. "
.ti -1c
.RI "bool \fBRealizarCheckInRegras\fP (int codigoReserva)"
.br
.RI "Realiza o check-in para a reserva especificada\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Purpose: Created by: João Barbosa Created on: 18/12/2024 11:23:58\&. 


.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "Regras\&.RegrasCheckIn\&.RegrasCheckIn ()"

.PP
Construtor da classe \fBRegrasCheckIn\fP\&. Inicializa uma nova instância de GestaoCheckIn\&. 
.SH "Documentação das funções"
.PP 
.SS "bool Regras\&.RegrasCheckIn\&.AdicionarCheckInRegra (\fBCheckInBO\fP checkIn)"

.PP
Adiciona um check-in à gestão de check-ins\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcheckIn\fP O check-in a ser adicionado\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se o check-in foi adicionado com sucesso, caso contrário, retorna \fRfalse\fP\&.
.RE
.PP

.SS "bool Regras\&.RegrasCheckIn\&.CarregarCheckInsRegra (string caminhoFicheiro)"

.PP
Carrega os check-ins a partir de um ficheiro\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP Caminho do ficheiro de onde os check-ins serão carregados\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se os check-ins foram carregados com sucesso, caso contrário, retorna \fRfalse\fP\&.
.RE
.PP

.SS "bool Regras\&.RegrasCheckIn\&.GuardarCheckInsRegra (string caminhoFicheiro)"

.PP
Guarda os check-ins em um ficheiro\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcaminhoFicheiro\fP Caminho do ficheiro onde os check-ins serão guardados\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se os check-ins foram guardados com sucesso, caso contrário, retorna \fRfalse\fP\&.
.RE
.PP

.SS "bool Regras\&.RegrasCheckIn\&.RealizarCheckInRegras (int codigoReserva)"

.PP
Realiza o check-in para a reserva especificada\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoReserva\fP Código da reserva para a qual o check-in será realizado\&.
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna \fRtrue\fP se o check-in foi realizado com sucesso, caso contrário, retorna \fRfalse\fP\&.
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
