.TH "Regras" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Regras
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBRegrasCheckIn\fP"
.br
.RI "Purpose: Created by: João Barbosa Created on: 18/12/2024 11:23:58\&. "
.ti -1c
.RI "class \fBReservasRegras\fP"
.br
.RI "Purpose: Created by: João Barbosa Created on: 17/12/2024 16:27:39\&. "
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
