.TH "Regras/ReservasRegras.cs" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Regras/ReservasRegras.cs
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBRegras\&.ReservasRegras\fP"
.br
.RI "Purpose: Created by: João Barbosa Created on: 17/12/2024 16:27:39\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRegras\fP"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
