.TH "BO/ReservasBO.cs" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BO/ReservasBO.cs
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBBO\&.ReservaBO\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBO\fP"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
