.TH "ReservasTests.ReservasTests" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReservasTests.ReservasTests
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.RI "Inicializa uma nova instância da classe Reservas antes de cada teste\&. "
.ti -1c
.RI "void \fBAdicionarReservaValida\fP ()"
.br
.RI "Testa o método \fBReservas\&.AdicionarReserva\fP com uma reserva válida\&. Verifica se o código da reserva retornado é diferente de -1 e corresponde ao valor esperado\&. "
.ti -1c
.RI "void \fBAdicionarReservaInvalida\fP ()"
.br
.RI "Testa o método \fBReservas\&.AdicionarReserva\fP com uma reserva inválida (data de saída anterior à data de entrada)\&. Verifica se o código retornado é -1\&. "
.ti -1c
.RI "void \fBAdicionarReservaQuartosNegativos\fP ()"
.br
.RI "Testa o método \fBReservas\&.AdicionarReserva\fP com uma reserva contendo uma quantidade negativa de quartos\&. Verifica se o código retornado é -1\&. "
.in -1c
.SH "Documentação das funções"
.PP 
.SS "void ReservasTests\&.ReservasTests\&.AdicionarReservaInvalida ()"

.PP
Testa o método \fBReservas\&.AdicionarReserva\fP com uma reserva inválida (data de saída anterior à data de entrada)\&. Verifica se o código retornado é -1\&. 
.SS "void ReservasTests\&.ReservasTests\&.AdicionarReservaQuartosNegativos ()"

.PP
Testa o método \fBReservas\&.AdicionarReserva\fP com uma reserva contendo uma quantidade negativa de quartos\&. Verifica se o código retornado é -1\&. 
.SS "void ReservasTests\&.ReservasTests\&.AdicionarReservaValida ()"

.PP
Testa o método \fBReservas\&.AdicionarReserva\fP com uma reserva válida\&. Verifica se o código da reserva retornado é diferente de -1 e corresponde ao valor esperado\&. 
.SS "void ReservasTests\&.ReservasTests\&.Setup ()"

.PP
Inicializa uma nova instância da classe Reservas antes de cada teste\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
