.TH "trataProblemas" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trataProblemas
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBAcessoNegadoException\fP"
.br
.RI "Exceção lançada quando o acesso é negado\&. "
.ti -1c
.RI "class \fBBaseReservaException\fP"
.br
.RI "Classe base para as exceções do sistema de reservas\&. "
.ti -1c
.RI "class \fBErroDeIOException\fP"
.br
.RI "Exceção lançada devido a um erro de entrada/saída\&. "
.ti -1c
.RI "class \fBFicheiroNaoEncontradoException\fP"
.br
.RI "Exceção lançada quando um ficheiro não é encontrado\&. "
.ti -1c
.RI "class \fBSerializacaoException\fP"
.br
.RI "Exceção lançada quando ocorre um erro de serialização\&. "
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
