.TH "trataProblemas/trata.cs" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trataProblemas/trata.cs
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBtrataProblemas\&.BaseReservaException\fP"
.br
.RI "Classe base para as exceções do sistema de reservas\&. "
.ti -1c
.RI "class \fBtrataProblemas\&.AcessoNegadoException\fP"
.br
.RI "Exceção lançada quando o acesso é negado\&. "
.ti -1c
.RI "class \fBtrataProblemas\&.ErroDeIOException\fP"
.br
.RI "Exceção lançada devido a um erro de entrada/saída\&. "
.ti -1c
.RI "class \fBtrataProblemas\&.SerializacaoException\fP"
.br
.RI "Exceção lançada quando ocorre um erro de serialização\&. "
.ti -1c
.RI "class \fBtrataProblemas\&.FicheiroNaoEncontradoException\fP"
.br
.RI "Exceção lançada quando um ficheiro não é encontrado\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtrataProblemas\fP"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
