.TH "trataProblemas.BaseReservaException" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trataProblemas.BaseReservaException \- Classe base para as exceções do sistema de reservas\&.  

.SH SYNOPSIS
.br
.PP
.PP
Derivada de Exception\&.
.PP
Herdado por \fBtrataProblemas\&.AcessoNegadoException\fP, \fBtrataProblemas\&.ErroDeIOException\fP, \fBtrataProblemas\&.FicheiroNaoEncontradoException\fP e \fBtrataProblemas\&.SerializacaoException\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBBaseReservaException\fP (string codigoErro)"
.br
.RI "Inicializa uma nova instância da classe \fBBaseReservaException\fP com o código de erro especificado\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Classe base para as exceções do sistema de reservas\&. 
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "trataProblemas\&.BaseReservaException\&.BaseReservaException (string codigoErro)"

.PP
Inicializa uma nova instância da classe \fBBaseReservaException\fP com o código de erro especificado\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigoErro\fP Código de erro associado à exceção\&.
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
