.TH "trataProblemas.SerializacaoException" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trataProblemas.SerializacaoException \- Exceção lançada quando ocorre um erro de serialização\&.  

.SH SYNOPSIS
.br
.PP
.PP
Derivada de \fBtrataProblemas\&.BaseReservaException\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBSerializacaoException\fP ()"
.br
.RI "Inicializa uma nova instância da classe \fBSerializacaoException\fP com um código de erro padrão (-3)\&. "
.in -1c

Membros públicos herdados de \fBtrataProblemas\&.BaseReservaException\fP
.in +1c
.ti -1c
.RI "\fBBaseReservaException\fP (string codigoErro)"
.br
.RI "Inicializa uma nova instância da classe \fBBaseReservaException\fP com o código de erro especificado\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Exceção lançada quando ocorre um erro de serialização\&. 
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "trataProblemas\&.SerializacaoException\&.SerializacaoException ()"

.PP
Inicializa uma nova instância da classe \fBSerializacaoException\fP com um código de erro padrão (-3)\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
