.TH "trataProblemas.ErroDeIOException" 3 "Gestão de Alojamentos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trataProblemas.ErroDeIOException \- Exceção lançada devido a um erro de entrada/saída\&.  

.SH SYNOPSIS
.br
.PP
.PP
Derivada de \fBtrataProblemas\&.BaseReservaException\fP\&.
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBErroDeIOException\fP ()"
.br
.RI "Inicializa uma nova instância da classe \fBErroDeIOException\fP com um código de erro padrão (-2)\&. "
.in -1c

Membros públicos herdados de \fBtrataProblemas\&.BaseReservaException\fP
.in +1c
.ti -1c
.RI "\fBBaseReservaException\fP (string codigoErro)"
.br
.RI "Inicializa uma nova instância da classe \fBBaseReservaException\fP com o código de erro especificado\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Exceção lançada devido a um erro de entrada/saída\&. 
.SH "Documentação dos Construtores & Destrutor"
.PP 
.SS "trataProblemas\&.ErroDeIOException\&.ErroDeIOException ()"

.PP
Inicializa uma nova instância da classe \fBErroDeIOException\fP com um código de erro padrão (-2)\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Gestão de Alojamentos a partir do código fonte\&.
